# Site settings
title: Wubing Wang
email: king@bbking.me
description: > # this means to ignore newlines until "baseurl:"
  Wubing Wang's Personal Page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bbking.me" # the base hostname & protocol for your site
github_username:  wubingwang

# Build settings
markdown: kramdown
